### ISSUE TITLE
[BUG] Probe hangs if included: @AZP-0.1

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#102]
**Describe the bug**
Running Pod Security Policy tests results in a +20 minute freeze when running `Prevent deployments from accessing unapproved port range`

**To Reproduce**
1. Run probr with `loglevel=DEBUG`
2. It freezes

**Expected behavior**
Shouldn't freeze

**Screenshots**
N/A

**Additional context**
Last log is from: 
`iShouldNotBeAbleToPerformACommandThatAccessAnUnapprovedPortRange`->`runVerificationProbe`->`ExecPSPProbeCmd`->
`ExecCommand`

**Comment by rparupell** [comment]
I included below steps in feature file and ran debug multiple times with loglevel=DEBUG I don’t see any delay in execution.

Also included the below steps in other scenarios and tried running them and still I don’t see any issue.

    //AZPolicy - port range
    ctx.Step(`^an "([^"]*)" port range is requested for the Kubernetes deployment$`, ps.anPortRangeIsRequestedForTheKubernetesDeployment)
    ctx.Step(`^I should not be able to perform a command that access an unapproved port range$`, ps.iShouldNotBeAbleToPerformACommandThatAccessAnUnapprovedPortRange)
    ctx.Step(`^some system exists to prevent Kubernetes deployments with unapproved port range from being deployed to an existing Kubernetes cluster$`, ps.someSystemExistsToPreventKubernetesDeploymentsWithUnapprovedPortRangeFromBeingDeployedToAnExistingKubernetesCluster)
