### ISSUE TITLE
[BUG] Scenario for creation of Pod from image from unauthorised repository fails because of invalid ImageRef

### ISSUE THREAD

**Issue by paulm-jones** [citihub/probr#121]
**Describe the bug**
We have the following Scenario:

```cucumber
  @preventative @CIS-6.1.5
  Scenario: Ensure deployment from an unauthorised container registry is denied
    Given a Kubernetes cluster is deployed
    When a user attempts to deploy a container from an unauthorised registry
    Then the deployment attempt is denied
```

We have default configuration:

```go
	e.set(&e.AuthorisedContainerRegistry, "PROBR_AUTHORISED_REGISTRY", "docker.io")
	e.set(&e.UnauthorisedContainerRegistry, "PROBR_UNAUTHORISED_REGISTRY", "")
	e.set(&e.ProbeImage, "PROBR_PROBE_IMAGE", "citihub/probr-probe")
```

We build an image ref by prefixing with "/":

```go
func (c *CRA) SetupContainerAccessProbePod(r string, probe *summary.Probe) (*apiv1.Pod, *kubernetes.PodAudit, error) {
	//full image is the repository + the configured image
	i := r + "/" + config.Vars.ProbeImage
        ...
```

With `r=""` this means we end up with `/citihub/probr-probe` which is an invalid image reference (we should have `citihub/probr-probe`).

Deployment therefore fails, but not for the reason we expect.

**To Reproduce**
1. Run `probr` with default config
1. Observe the KubeEvent logs in the Log Analytics Workspace that is now attached to `probr-demo-cluster`

```kusto
KubeEvents
| project TimeGenerated, Reason, Message
| where TimeGenerated >= ago(30min)
| order by TimeGenerated desc
```

|TimeGenerated|Reason|Message|
|---|---|---|
| 12/2/2020, 9:46:43.000 PM | Failed | Error: InvalidImageName |  
| 12/2/2020, 9:46:43.000 PM | InspectFailed | Failed to apply default image tag "/citihub/probr-probe": couldn't parse image reference "/citihub/probr-probe": invalid reference format |

**Expected behavior**
1. We should drop a leading "/" from an imageRef
1. We do try to check that error we get is the error we expect but I am not sure the function is correct

We fail at `When a user attempts to deploy a container from an unauthorised registry`, i.e. a step earlier than we would like.

If this had worked we would hit `kubernetes.AssertResult(&s.podState, "denied", "")`, but `AssertResult` does nothing with `msg` (the parameter should really be removed). I can't quite reason it through without debugging it but I am not sure where `*s.ExpectedReason` comes from (for us to look up the right reason).

**Screenshots**
<img width="537" alt="image" src="https://user-images.githubusercontent.com/9488971/100939923-06bfe700-34ef-11eb-9475-05236b146dac.png">

**Additional context**
N/A

**Comment by simonwoolhouse** [comment]
Should we make AuthorisedContainerRegistry and UnauthorisedContainerRegistry config variables mandatory?

We default AuthorisedContainerRegistry to "docker.io", which for most clients is probably incorrect
We default UnuthorisedContainerRegistry to "" which causing this issue. Again, clients should specify a registry they don't allow

**Comment by paulm-jones** [comment]
As discussed on the call earlier, yes, I think it makes sense to make the configuration mandatory, as you correctly point out that we don't necessarily know which registries will be permitted and which will not.

Alone, I am not sure if that's enough, because even if we do have a named unauthorised registry (let's say for the sake of argument mcr.io), I am not sure we can reliably tell the difference between:

- firewall blocks access
- we can hit the registry but it doesn't authorise us
- we can hit the registry and don't need authentication but it doesn't have the container we asked for

I think we have to name an image as well that we know is definitely there and we know will definitely be blocked.

**Comment by eddie-knight** [comment]
The "bug" part of this issue (highlighted in the title) has been resolved by making the registry values mandatory. 

If there are any other suggestions here that we can/should apply, please raise them in a new issue! Thanks!
