### ISSUE TITLE
[FEATURE] include version of benchmark or standard in tag references

### ISSUE THREAD

**Issue by paulm-jones** [citihub/probr#134]
**Is your feature request related to a problem? Please describe.**

We currently reference CIS benchmarks with tags on Features and Scenarios, e.g (abridged):

```cucumber
  @standard/cis/gke/6.10.1
  Scenario: Ensure Kubernetes Web UI is disabled
    Then the Kubernetes Web UI is disabled
```

We do not know which _version_ of the CIS Benchmark this references. For example, section 6.10.1 does not exist in the version from a few months ago, it has been added recently. We also cannot guarantee that sections will not move around over time, breaking our references.

**Describe the solution you'd like**
- We update our references to include the version of the document in question. This would allow us the flexibility to mix and match versions if we wanted, but I don't think that's desirable.

For example `@standard/cis/gke/6.10.1` could become `@standard/cis/gke/v1.6.0/6.10.1

**Describe alternatives you've considered**
- We declare a "dependencies" file (a bit like `go.mod`) in the root of the repository that references the documents to which we refer / against which we have built our tags. This would be simple, but I think it is too undiscoverable.

**Additional context**
N/A

**Comment by iantivey** [comment]
Agreed

**Comment by lcarrazana** [comment]
- [ ] Get a copy of CIS Benchmark

**Comment by lcarrazana** [comment]
#209 
#211
