### ISSUE TITLE
[FEATURE] Integrate audit/summary logging to Storage SP

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#145]
**Is your feature request related to a problem? Please describe.**
Storage service pack does not currently output summary or audit logs

**Describe the solution you'd like**
Audit and Summary handling should be similar to the Kubernetes service pack.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lcarrazana** [comment]
- [ ] For each step function in Storage service pack, add description and payload with relevant data (args, local vars)
- [ ] Enable Storage service pack in probr config file (examples/config.yml)
- [ ] Run probr against Azure and check storage output
