### ISSUE TITLE
[FEATURE] Assume Resource Group already exists

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#147]
**Is your feature request related to a problem? Please describe.**
Currently the storage account pack creates a resource group in code.  We should assume a resource group already exists for us to deploy into.

**Describe the solution you'd like**
Pass in the name of the resource group in config.yml and use that instead of creating them.

**Describe alternatives you've considered**

**Additional context**
Many of our clients are handing out pre-provisioned resource groups to app teams.

**Comment by eddie-knight** [comment]
This was resolved by PR #158
