### ISSUE TITLE
[FEATURE] Revise K8s scenario state structs

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#172]
**Is your feature request related to a problem? Please describe.**
The scenarioState structs in the K8s SP are copy-pasted across all of the probes. Many of the fields in the pasted-structs are not used by each probe. This impacts readability dramatically.

**Describe the solution you'd like**
Any unused fields should be removed.

**Describe alternatives you've considered**
n/a 

**Additional context**
n/a

**Comment by lcarrazana** [comment]
Raj

- [ ] kubernetes/container_registry_access
- [ ] kubernetes/general

Luis
- [ ] kubernetes/iam
- [ ] kubernetes/internet_access
- [ ] pod_security_policy
