### ISSUE TITLE
[FEATURE] Detailed audit log

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#19]
**Is your feature request related to a problem? Please describe.**
If an auditor wants to dive into exactly how a test is being executed the only way to do that currently is to dive into the code.  A detailed audit log showing the request/response for each step would avoid code-level analysis and provide an easier mechanism for describing how any individual probe run was executed.

**Describe the solution you'd like**

An output which is the same format as the summary log, but with additional execution detail.  Roughly like this:
```
"Steps": {
  "aPodIsDeployedInTheCluster": {
    "Result": "Failed",
    "TestExecutionDetail": [
        {
          "Order": "1",
          "Request": {
            "Type": "Kubernetes.Deployment",
            "Payload": {
              //json representation of the Kubernetes deployment
            }
          },
          "Response": {
            "Type": "Kubernetes.Response",
            "Payload": {
              //json representation of the Kubernetes response
            }
          }
        },
        {
          "Order": "2",
          "Request": {
            "Type": "Kubernetes.exec",
            "Payload": {
              "/bin/sh -c ls"
            }
          },
          "Response": {
            "Type": "Kubernetes.exec_response",
            "Payload": {
              //a json representation of the exec response
            }
          }
        }
      }
    ]
  }
}
```

**Additional context**

**Comment by eddie-knight** [comment]
**Engineering Note:** Previously we used the term "audit log" for what has recent been renamed to "summary." The feature described in this issue is more deserving of the name "audit log" because it will be a detailed audit of the steps taken by an individual probe.

**Comment by eddie-knight** [comment]
Resolved this incrementally with several of the recent PRs. The new "summary" feature is writing this detailed information to files created for each probe. @simonwoolhouse will be increasing documentation for this feature as part of a larger movement to increase documentation in coming days/weeks.
