### ISSUE TITLE
[FEATURE] Refactor PSP for readability

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#210]
**Is your feature request related to a problem? Please describe.**
Currently it is difficult to debug or suggest improvements for the k8s pod security policy probe.

**Describe the solution you'd like**
It is important that these changes are _non-functional_ only.

Please modify these files to change all variable names to be self-descriptive, using full English-language names:
https://github.com/citihub/probr/blob/main/service_packs/kubernetes/pod_security_policy/helpers.go
https://github.com/citihub/probr/blob/main/service_packs/kubernetes/pod_security_policy/pod_security_policy.go
https://github.com/citihub/probr/blob/main/service_packs/kubernetes/pod_security_policy/azk8sconstrainttemplate.go

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by iantivey** [comment]
There's a branch in my fork which changes some of the fundamental BDD specs.  Please don't work on this issue until you've look at the fork.  I can always raise a PR into your fork if you want to finish it off.

**Comment by lcarrazana** [comment]
Address potential issue in pod_security_policy.go line 147

![image](https://user-images.githubusercontent.com/62344673/107044410-42e32280-6792-11eb-98b0-270a0909c5e1.png)

**Comment by eddie-knight** [comment]
I believe a general refactoring can begin on this, so long as the step names and logic _do not change_.

Acceptance criteria: 
- A nice overhaul on the variable and function naming in the aforementioned files
- Create issues for any bugs identified during refactoring
- Create any helpful _NONFUNCTIONAL_ logic changes to increase readability

**Comment by lcarrazana** [comment]
Regression test before starting:
`go run .\cmd\main.go --varsfile=config.yml --tags=@k-psp`

**Comment by lcarrazana** [comment]
- [ ] helpers.go
- [ ] pod_security_policy.go
- [ ] azk8sconstrainttemplate.go
