### ISSUE TITLE
[FEATURE] Migrate from Packr to Pkger

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#216]
**Is your feature request related to a problem? Please describe.**
Previously we have been able to build and run Probr as a standalone binary executable, but that isn't currently the case. Packr, which we are using to enable that no-longer-functional behavior, recommends migrating to Pkger instead. Perhaps we can resolve the build problem while migrating dependencies.

**Describe the solution you'd like**
Remove all Packr logic and replace it with Pkger. Ensure that the resulting behavior allows Probr to be run as a standalone binary executable (instead of requiring the source code for execution).

**Describe alternatives you've considered**
I suppose we could contrive a process that installs probr to a machine without requiring it to be packaged.

**Additional context**
n/a

pkger ref : https://github.com/markbates/pkger

**Comment by lcarrazana** [comment]
Steps to replicate current issue with Packr:

- Build executable: `go build -o probr ./cmd/main.go`
- Run probr from anywhere except root folder:
- `cd ..`
- `./probr/probr --varsfile=./probr/config.yml --loglevel=WARN`
- An error should be raised: `feature path "service_packs\storage\azure\encryption_at_rest\encryption_at_rest.feature" is not available`

After migrating to Pakger above error should dissapear
