### ISSUE TITLE
[FEATURE] Remove incomplete service packs from Probr core

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#218]
**Is your feature request related to a problem? Please describe.**
Currently all service packs are built in the same source code as the Probr core. This causes a few potential issues:

1. Probr core requires versioning even if only probes are modified
2. Active progress on probes is often distracted by opportunities for improvement on Probr core
3. Documentation for probes and service packs is blended together with Probr core documentation
4. Incomplete, prototype, or placeholder service packs live alongside feature-ready service packs

Similar to Terraform (though not identical in execution), version iterations should be much slower for Probr core, to show that it is stable and ready for users to introduce into their workflows.

**Describe the solution you'd like**
Create a policy outlining the conditions a service pack must meet before it can be migrated into the Probr core.

This policy may be informal for now, as no service packs are anywhere near feature-complete.

In execution, we'll simply move each of the service packs to a new repository- and change the import to target that new URL.

**Describe alternatives you've considered**
We could delay or avoid this entirely, but I think if we're _ever_ going to segment incomplete packs, now is the best time to do that.

**Additional context**
n/a

**Comment by lluuiissoo** [comment]
Have we considered a plug-in architecture, where each service pack is independently loaded and executed by the core engine ?
Having something like this will help with all issues above, plus stability: rogue probe implementations wouldn’t affect the core engine and other probes in a drastic way. 

The go-plugin package from Hashicorp looks interesting. 
https://github.com/hashicorp/go-plugin

**Comment by lcarrazana** [comment]
Have we considered a plug-in architecture?
Having totally independent service packs  would improve stability: rogue probe implementations wouldn’t affect the core engine and other probes in a drastic way.

The go-plugin package from Hashicorp looks interesting.
https://github.com/hashicorp/go-plugin

**Comment by eddie-knight** [comment]
The above PRs help make our repo compatible with external service packs. We still need to address how the files will be read when importing an external service pack. Marking this as blocked until I finish the research on that.

**Comment by eddie-knight** [comment]
If [this PR to Godog](https://github.com/cucumber/godog/pull/374) is merged, we'll be golden. If not, we'll need to either scrap this idea or use a Godog fork that has the feature from the PR above. (The fork would be upstream-maintainable, since it only adds a feature instead of modifying anything)

Keeping this in the "blocked" column until the aforementioned is resolved.

**Comment by eddie-knight** [comment]
Closed the aforementioned Godog PR as it seems it wasn't a fit for their scope. We're currently investigating go plugins and hashicorp's go-plugin as potential solutions.
