### ISSUE TITLE
[FEATURE] Move all Probr write activities to a single parent directory

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#223]
**Is your feature request related to a problem? Please describe.**
The audit output and cucumber output created by Probr are both being written to different directories specified by the user's config. This adds a layer of complexity when users want to target a single directory for CICD artifacts.

**Describe the solution you'd like**
1. Please remove both of the output config var options, replacing them with a single "WriteDirectory" variable.
    - For now, we should not create a default value for this. Probr should exit if this value is not provided by the user via a flag, config var, or env var.
2. Something along the lines of these changes should happen throughout the codebase:
    - `Config.Vars.CucumberDir` to `Config.Vars.WriteDirectory + "/output"`
    - `Config.Vars.AuditDir` to `Config.Vars.WriteDirectory + "/audit"`

**Describe alternatives you've considered**
n/a

**Additional context**
We will be using this directory for `tmp/` as well in the future.

**Comment by lcarrazana** [comment]
TODO:

- [ ] Add field to ConfigVars struct
- [ ] Add default value
- [ ] Update sample config file
- [ ] Update readme.md
  - [ ] Add WriteDirectory
  - [ ] Remove references to CucumberDir and AuditDir

**Comment by lcarrazana** [comment]
**Test**

| Test Case | Description | Expected Result | Result |
|---|---|---|---|
| Config only | Set value in config.yml: `WriteDirectory: out` - No value is set for env var or cli flag. | Value taken from config file. Folder specified in config file _out_ shall be created. _audit_ and _cucumber_ folders are created within write directory | Pass |
| CLI | Set value in config.yml: `WriteDirectory: out` - No value for env var - Pass value as cli argument: `--writedirectory=outcli`. | Value is taken from cli arg. Folder specified in cli arg _outcli_ shall be created. _audit_ and _cucumber_ folders are created within write directory | Pass |
| Env Var | Remove value from config.yml - Set env var: `PROBR_WRITE_DIRECTORY=outenvvar`  - No value passed as cli argument. | Value is taken from env var. Folder specified in env var _outenvvar_ shall be created. _audit_ and _cucumber_ folders are created within write directory | |
