### ISSUE TITLE
[FEATURE] Feature packing logic

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#224]
**Is your feature request related to a problem? Please describe.**
Extension of issue #216. Migrating to Packr will not be enough to resolve the root problem (though that does need to happen). We have identified that Godog is attempting to read from the local filesystem at the time of execution, and no amount of "packing" files into file-like objects will stop Godog from doing it's I/O against the local filesystem.

**Describe the solution you'd like**
Please maintain the current Packr logic to store feature file content in the binary, but add additional logic to Probr core that will write feature files at runtime to the `tmp` created in #223. Pass the new temp file path to Godog

**Describe alternatives you've considered**
The alternative option that was discussed is to ship the feature files alongside the binary.

**Additional context**
n/a

**Comment by lcarrazana** [comment]
- [ ] Include all feature files for pkger bundling
- [ ] On init, iterate thru all probes, load feature files from pkger in-memory buffer and save them to _tmp_ location
- [ ] On coreengine.GetFeaturePath, prepend _tmp_ location to read from file system

**Comment by lcarrazana** [comment]
**Aceptance Test**

| Step | Description | Action | Expected Result | Passed |
|---|---|---|---|---|
|1|Bundle static files|run `pkger`|A file named `pkged.go` is generated|---|
|2|Build probr binary|run `go build -o probr ./cmd/main.go`|A file named `probr` is generated|---|
|3|Copy binary and config file to a different location. e.g.: c:\temp\probr0.x\ |Copy files `probr` and `config.yml` to `c:\temp\probr0.x\` |Files are copied|---|
|4|Execute binary|For windows rename `probr` to `probr.exe` - run `probr.exe --varsfile=config.yml`|Application is executed, all probe tests are completed|---|
|5|Check `tmp` folder is generated during execution|---|---|---|
|6|Check `tmp` folder is deleted after execution|---|---|---|
