### ISSUE TITLE
[FEATURE] Improve code readability regarding Tests/Events

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#25]
**Is your feature request related to a problem? Please describe.**
Presently the code has a frequent use of the terminology "Test," to describe BDD feature file executions. This is accurate, but it has caused confusion for new contributors. Currently the terminology Test, Feature, and Event are used almost interchangably, with the exception that Test may also describe integration or unit tests.

It has been brought to our attention that the addition of "Probe" being interchangable with _scenarios_ is adding to the aforementioned confusion.

**Describe the solution you'd like**
- All situations where the word "Test" is used to describe a core Probr functionality should be revised to use a more descriptive term. 
- All current uses of "Probe" should be modified to use "Scenario"
- All Tests/Events/Features should be changed to the term "Probe"

**Describe alternatives you've considered**
The value of leaving this as-is has been discussed, but currently the consensus is that "Test" should _only_ be used to describe any elements that test Probr (and "test" should _not_ be used to describe anything related to probes). 

Previously we were moving toward using the term Event for tests/features, and Probe for scenarios.

This task applies to everything from variables and functions to comments and docs.

**Comment by eddie-knight** [comment]
Updated this task with feedback from @simonwoolhouse to include reducing the number of name substitutions. The only substitution we should have after this task is `Probes == Features`.

**Comment by simonwoolhouse** [comment]
Widespread change from Test/Event terminology to Probe
