### ISSUE TITLE
[BUG] Address potential issue in pod_security_policy.go line 147

### ISSUE THREAD

**Issue by lcarrazana** [citihub/probr#255]
**Describe the bug**

**To Reproduce**
1. Run probr and target scenario @k-psp-005 
2. Add debug breakpoint inside function `runVerificationProbe` line 147 (see //TODO comment)
3. Error returned from k8s client is not handled

**Expected behavior**
Error returned from k8s should be handled appropriately

**Screenshots**
![image](https://user-images.githubusercontent.com/62344673/107056112-ff8fb080-679f-11eb-9164-5bdc180c83b7.png)

**Comment by lcarrazana** [comment]
After reviewing and debugging `iShouldNotBeAbleToPerformASudoCommandThatRequiresPrivilegedAccess` function, it was confirmed that highlighted behavior works as expected.
- In the event of Internal error before command is executed, test fails with error
- In the event of error produced by command itself, test checks expected exit code and fails or succeeds accordingly

**Comment by lcarrazana** [comment]
Additional proposed enhancements to @k-psp-005:
```
@k-psp-005
    Scenario Outline: Prevent a deployment from running with the allowPrivilegeEscalation flag
        Given a Kubernetes cluster exists which we can deploy into
        And some system exists to prevent a Kubernetes deployment from running using the allowPrivilegeEscalation in an existing Kubernetes cluster
        When a Kubernetes deployment is applied to an existing Kubernetes cluster
        And privileged escalation is marked "<AllowPrivilegeEscalation requested>" for the Kubernetes deployment
        Then the operation will "<RESULT>" with an error "<ERRORMESSAGE>"
        But I should not be able to perform a sudo command that requires privileged access
        And I should be able to perform an allowed command

        Examples:
            | AllowPrivilegeEscalation requested | RESULT        | ERRORMESSAGE                                                   |
            | True                               | Fail          | Containers cant run using the allowPrivilegeEscalation flag |
            | False                              | Succeed       | No error would show                                         |
            | Not Defined                        | Succeed       | No error would show                                         |
```

**Comment by eddie-knight** [comment]
Lets see if we can cover these comments in #210, and if any new issues need made we can create those new issues while working on the refactoring.

This comment will create an entry on the other issue, so we can review these notes as needed while working on it.
