### ISSUE TITLE
[FEATURE] Improve BDD readability

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#265]
**Is your feature request related to a problem? Please describe.**
Paul has started progress on adjusting the BDD language, but his branch is out of date & needs more work than he has time for.

**Describe the solution you'd like**
Review the changes propsed [here](https://github.com/paulm-jones/probr/tree/kube-feature-runthrough) and manually copy them over. Make necessary adjustments to the step logic. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lcarrazana** [comment]
The following changes are being merged:
- [ ] Feature files for k8s future implementation
- [ ] Container Registry Access
- [ ] General
- [ ] IAM
- [ ] Internet Access
- [ ] Pod Security Policy

**Comment by eddie-knight** [comment]
The observations gathered during the preliminary work for this PR are now logged in issues 326-346. As such, I'm closing this issue and we'll be forwarding all further conversation to the related issues.

All of those issues have been tagged with `kubernetes`, `bdd`, `refactor`
