### ISSUE TITLE
[FEATURE] Unapproved Volume Type step not implemented

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#271]
**Is your feature request related to a problem? Please describe.**
We have not yet written logic for the step `iShouldNotBeAbleToPerformACommandThatAccessesAnUnapprovedVolumeType`

**Describe the solution you'd like**
Research and then implement the necessary logic

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by iantivey** [comment]
Removed the command - it doesn't make sense to run a command against volume type.
