### ISSUE TITLE
[BUG] - Investigate and fix failing PSP probes - unapproved volume types

### ISSUE THREAD

**Issue by lcarrazana** [citihub/probr#289]
**Describe the bug**
When running all PSP probes, we are consistently getting 3 failed scenarios.
These failures correspond to 
- @k-psp-010
   Scenario Outline: Prevent deployments from accessing unapproved volume types

**To Reproduce**
1. Run `probr --tags=@k-psp` against Demo Cluster
2. When finished, see final result in shell output: `"ScneariosFailed": 3,`
3. Open audit logs `probr_output/audit/pod_security_policy.json`
4. Search for `"Result": "Failed"`

**Expected behavior**
All three test cases within k-psp-010 scenario shall succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/62344673/107827645-342dda00-6d55-11eb-94f6-689453560398.png)

---

![image](https://user-images.githubusercontent.com/62344673/107827930-c0d89800-6d55-11eb-961a-7012ab8f42e2.png)

**Additional context**
n/a

**Comment by eddie-knight** [comment]
This was failing due to the secrets volume not being accounted for in the probe
