### ISSUE TITLE
[FEATURE] Fully compliant terraform cluster

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#29]
**Is your feature request related to a problem? Please describe.**
The current cluster deployed by the terraform example is far from "green" and does not give a comprehensive example of what Probr can achieve.

**Describe the solution you'd like**
Enhance the current terraform cluster so that it produces a fully compliant terraform cluster.

**Describe alternatives you've considered**
We have delayed this due to it not being a critical need, but we shouldn't continue delaying it indefinitely.

**Comment by eddie-knight** [comment]
When this is complete, create another issue to track work for terraforming a "red" cluster (I just don't want to overcrowd the backlog)

**Comment by iantivey** [comment]
This is now in the demo gitlab master branch.  The only think I'm not confident about is the AzureIdentity tests - see separate issues for those.

**Comment by medwards1976** [comment]
After analyzing @iantivey code, my opinion that I should create the ability for Terraform to create Kubernetes clusters on developers and client administrators local machines using Azure CLI, and CloudShell in Azure. The future can be docker image and Azure Devops.

**Comment by eddie-knight** [comment]
Closing this now that we've got a dev workflow available in https://github.com/citihub/probr-cloud
