### ISSUE TITLE
[BUG] All probes are deploying a volume of type secret

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#299]
**Describe the bug**
All (or majority) of our probes are deploying a Kubernetes volumeType of `secret`.  This is conflicting with the approved volumeTypes probe.

**To Reproduce**
Add `Kubernetes cluster pods should only use allowed volume types` Azure Policy to a cluster, which doesn't have `secret` in the allowed volume types field.

Run Probr against it (you might have to wait for the Azure Policy to take effect - 15-20 minutes in some cases)

**Expected behavior**
Probes don't fail due to "approved volume types" policy blocking admission into the cluster

**Additional context**
I don't think there's a good reason to include a volume type of secret in any of our Pods?

**Comment by eddie-knight** [comment]
The secret volume will be mounted for any pod that doesn't have `automountServiceAccountToken: false` set in the spec.

Do we have a CIS standard dictating that the SA token isn't mounted to all pods? If that's the case, leaving `secret` out of the azure policy is logical.

However, it should be noted that the aforementioned Azure Policy defaults to an empty list, which will reject all volume mounts. If we want to validate that policy, we'll need to create an issue for a new BDD and create a config var to handle the known volume types.

Moving this issue to the _discussion_ column for now. If possible, I'd like to close this issue and open a new one outlining the desired new features.
