### ISSUE TITLE
[BUG] Issue in IAM probe - Unexpected result when running command against MIC pod

### ISSUE THREAD

**Issue by lcarrazana** [citihub/probr#311]
**Describe the bug**
One scenario within IAM probe is failing.
```
Scenario: Prevent access to AKS credentials via Azure Identity Components
    When I execute the command "cat /etc/kubernetes/azure.json" against the MIC pod
    Then Kubernetes should prevent me from running the command
```
Root cause seems to be an unexpected result when running command.
The function `iExecuteTheCommandAgainstTheMICPod` is executing command, but never hits this line:
 `s.podState.CommandExitCode = res.Code`

**To Reproduce**
1. go run ./cmd/main.go --varsfile=config.yml --tags=@k-iam-003
2. When finished, see cucumber output for `iam.json`
3. Notice failure in step `Kubernetes should prevent me from running the command`

**Expected behavior**
- When executing command agains MIC pod, expected result is failure (exit code 126)
- Scenario should pass

**Screenshots**
![image](https://user-images.githubusercontent.com/62344673/108426712-17d4e600-720a-11eb-9b02-ad6c8fa9cc11.png)

**Additional context**
n/a

**Comment by iantivey** [comment]
Good spot. That should be `==`, not `!=`.

There's a general problem with parsing exit codes that we need to figure out.  The exit code from the `exec` API call doesn't mirror the exit code from the command that was executed. I'll open another issue.
