### ISSUE TITLE
[BUG] Exit codes returned by Kube API don't reflect the exit code inside the container

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#313]
**Describe the bug**
The exit code in `Res.Code` is the exit code of the Kubernetes API, not the exit code of the command that was run inside of the container.  More often than not this is "success" (exit 0) or "not executable" (exit 126) although we do occasionally get "cannot access command" (exit 2)

**To Reproduce**
Run an exec command that returns an exit code (don't choose 0, 2, 126 or 127)

Some examples I've tried:
`exit 99`
`echo "exit 99" > /tmp/exitcode.sh; source /tmp/exitcode.sh`
`echo "exit 99" > /tmp/exitcode.sh; chmod +x /tmp/exitcode.sh; /tmp/exitcode.sh`

I'd expect the exit code coming back from the API to be 99, but it returns an exit code of 0 (`res.Code == 0`)

If you run either of those commands directly on a host terminal you get the expected exit code

```
> echo "exit 99" > /tmp/exitcode.sh; chmod +x /tmp/exitcode.sh; /tmp/exitcode.sh
> $?
99
```

**Expected behavior**
`res.Code == 99`

**Comment by eddie-knight** [comment]
closing this as it's being discussed in the development of the k8s connection package
