### ISSUE TITLE
[BUG] Brittle IAM step 'iExecuteTheCommandAgainstTheMICPod'

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#320]
**Describe the bug**
The step `iExecuteTheCommandAgainstTheMICPod` in the IAM probe will be non-functional if the feature file is changed, because the argument passed from the feature file is not used by the step function.

**To Reproduce**
1. Adapt `k-iam-003` to use a different command in the parameter
2. Notice that the actual runtime will use the old command, because the argument passed is irrelevant to the functionality

**Expected behavior**
Modifying the parameter should adapt the step behavior accordingly.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by lcarrazana** [comment]
Implemented as described above in PR #377 
Please note TODO comments inside step function:
```
// TODO: Review this
// I think ANY command executed against MIC pod will return same 126 exit code.
// Potential cause is that 'mic' container image is based on 'distroless', which is
// a minimalistic OS version containing only application and runtime dependencies.
// It doesn't even have a shell.
// If this assumption is correct, then this step and associated scenario should be
// adjusted, since execution will always fail regardless of command, therefore causing
// false positives.
// Is there any other way to get access to Volume: /etc/kubernetes/azure.json ?
// Ref:
//  https://hub.docker.com/_/microsoft-k8s-aad-pod-identity-mic?tab=description
//  https://github.com/GoogleContainerTools/distroless
```
