### ISSUE TITLE
[FEATURE] Add configurable known role definitions that can be used in IAM probe

### ISSUE THREAD

**Issue by lcarrazana** [citihub/probr#325]
**Is your feature request related to a problem? Please describe.**
```
@k-iam-004
Scenario Outline: Minimise wildcards in Roles and Cluster Roles
```
Currently, there are no configurable known role definitions that can be used here.

**Describe the solution you'd like**
- Add configurable list of role definitions to _ServicePacks.Kubernetes.KnownRoleDefinitions_ config setting
- Update logic of @k-iam-004 probe, to exclude these known role definitions from check.

**Describe alternatives you've considered**
n/a

**Additional context**
See related comments in this PR https://github.com/citihub/probr/pull/310

**Comment by iantivey** [comment]
I started writing what was quite a complex response here, but then I realised that we're just inspecting configuration here so isn't really a Probr-style control test.

@paulm-jones - interested in your view on this

**Comment by eddie-knight** [comment]
@iantivey @paulm-jones
Do we want to remove this issue citing that it's not within the core probr approach?
