### ISSUE TITLE
[BDD] Remove k-gen scenarios

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#330]
Please remove k-gen-001 and do not replace it. If we wish to bring this back, the code may be found in release/tag `v0.8.0`. 

Issue #325 will approach the conversation around validating wildcard roles.

Additionally,@paulm-jones has suggested that we remove k-gen-002.

The following functions will no longer be necessary in `service_packs/kubernetes/general/general.go`:
- iInspectTheThatAreConfigured
- iShouldOnlyFindWildcardsInKnownAndAuthorisedConfigurations
- iAttemptToCreateADeploymentWhichDoesNotHaveASecurityContext
- theDeploymentIsRejected

**Comment by lcarrazana** [comment]
Removing the following scenario: **Scenario Outline: Minimise wildcards in Roles and Cluster Roles**
If code is needed it can be pulled back from commit history (before this PR)
