### ISSUE TITLE
[BUG] IAM probe - Error when attempting to retrieve access token

### ISSUE THREAD

**Issue by lcarrazana** [citihub/probr#383]
**Describe the bug**
Several scenarios in IAM probe attempt to retrieve access token from POD.
```
But an attempt to obtain an access token from that pod should "<RESULT>"
```
The corresponding curl command is raising an error in all cases: 
`Failed to acquire token on pod <podname> Error: invalid character 'g' looking for beginning of value StdOut: getting assigned identities for pod <namespace>/<podname> in CREATED state failed after 16 attempts, retry duration [5]s, error: \u003cnil\u003e. Check MIC pod logs for identity assignment errors\n`

**To Reproduce**
1. `go run .\cmd\main.go --varsfile=config.yml --tags=@k-iam`
2. Look at audit log `iam.json`
```
"4": {
          "Function": "anAttemptToObtainAnAccessTokenFromThatPodShouldX",
          "Name": "an attempt to obtain an access token from that pod should \"Succeed\"",
          "Description": "Attempt to run command in the pod: 'curl http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01\u0026resource=https%3A%2F%2Fmanagement.azure.com%2F -H Metadata:true -s'; Attempt to extract access token from command output; Validate token was found; ",
          "Result": "Failed",
          "Error": "Failed to acquire token on pod iam-120321-121456-39 Error: invalid character 'g' looking for beginning of value StdOut: getting assigned identities for pod default/iam-120321-121456-39 in CREATED state failed after 16 attempts, retry duration [5]s, error: \u003cnil\u003e. Check MIC pod logs for identity assignment errors\n",
          "Payload": null
        }
```

**Expected behavior**
- When expectation is Success, Access Token shall be retrieved
- When expectation is Fail, Access Token shall not be retrieved, but an appropriate error should be handled

**Screenshots**
n/a

**Additional context**
For troubleshooting, access a pod directly and execute command:
```
> kubectl exec -it <podname> -- sh

> curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s
```

**Comment by eddie-knight** [comment]
this applies to `k-iam-001` and `k-iam-002`
