### ISSUE TITLE
[FEATURE] Use config vars to manage loglevel

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#52]
**Is your feature request related to a problem? Please describe.**
Currently loglevel can only be specified via env vars.

**Describe the solution you'd like**
 Adjust the logger to use a config var, and add an appropriate entry to the config vars logic.

**Describe alternatives you've considered**
None.

**Additional context**
Change loglevel logic here: `internal\config\logfilter.go` -> lines 15 through 23 should use a config var instead of lookup
Add ConfigVars.LogLevel here: `internal\config\config.go` -> anywhere in the ConfigVars struct
Add default and env var support here: `internal\config\defaults.go` -> add an `e.set()` entry for "PROBR_LOGLEVEL" with the default set to "ERROR"

**Comment by simonwoolhouse** [comment]
Found an interesting problem. The logfilter init() function fires before the config file is read, so even if a LogLevel is set in the config.yml file, it is ignored and env var / default value takes precedence

**Comment by simonwoolhouse** [comment]
If a config file is provided, the config.Init() function gets called twice, once when config initializes with an empty file, and then after the config file has been parsed
