### ISSUE TITLE
[FEATURE] Adjust image target logic

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#53]
**Is your feature request related to a problem? Please describe.**
There was some confusion with a client who was using this; they were trying to figure out why their CI needed a busybox and curl image var.

**Describe the solution you'd like**
Perhaps curl and busybox don't need to be customizable as config vars? If they _do_ need to be customizable, let's change the var names to include the prefix `PROBR_` to avoid that confusion in the future.

**Describe alternatives you've considered**
None

**Additional context**
- `Images.Curl` is used here: `internal\clouddriver\kubernetes\iam.go` and `internal\clouddriver\kubernetes\networkaccess.go`
- `Images.BusyBox` is used here: `internal\clouddriver\kubernetes\podsecuritypolicy.go` and `probes\kubernetes\general_feature.go`
If these don't actually need to be customizable, they could be set as vars in the clouddriver/kubernetes package

**Comment by simonwoolhouse** [comment]
I don't believe images need to be configurable by the user, but should be set as constants in the Probr code. However, this is a more involved change, as the setting of image in the code is complex for some probes. For example, the image repository used in iam.go is overriden to "curlimages" if it is set to "docker.io" in Config.Vars
