### ISSUE TITLE
[FEATURE] Revise Tag Name Conventions

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#58]
**Is your feature request related to a problem? Please describe.**
Tags names are not always intuitive or consistent, and some feature-file tags aren't being utilized in real-world use.

**Describe the solution you'd like**
Refactor tags for consistency and practicality.

**Describe alternatives you've considered**
n/a

**Additional context**
Among other potential changes, things like `@CIS-x.x` could be revised to `@standards.CIS.x.x`

**Comment by simonwoolhouse** [comment]
@iantivey please expand upon your requirement to improve the way tags are used within feature files
Is simply renaming @CIS-x.x to @standards.CIS.x.x the primary requirement?

**Comment by simonwoolhouse** [comment]
It's not clear to me how the passing of tags as a command line argument eg. -tags="@CIS-1.2.3, @CIS-4.5.6" affects the running of probr. Does it determine which scenarios should be run? Is it documented?
