### ISSUE TITLE
[FEATURE] Review CLI Flags

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#75]
**Is your feature request related to a problem? Please describe.**
It'd be good to ensure that our flags match their config counterparts, and that they are all bug free

**Describe the solution you'd like**
Please go through the CLI flags with a fine-toothed comb and ensure that each is functioning exactly as expected. Flags should always take priority over other values, for example.

Additionally, please revise any names that have diverged from their config counterparts. This includes capitalization... there is no explicit reason to use a particular casing in `config.yml` _or_ in the CLI flags. Since it doesn't matter, let's make them identical.

**Describe alternatives you've considered**
none

**Additional context**
This issue is loosely correlated to issue #74

**Comment by simonwoolhouse** [comment]
Setting --OutputType="INMEM" correctly prevents the cucumber json output from being written to output files.
But the output is not directed to the terminal when run from the CLI. Is this correct behaviour?

**Comment by eddie-knight** [comment]
> Setting --OutputType="INMEM" correctly prevents the cucumber json output from being written to output files.
> But the output is not directed to the terminal when run from the CLI. Is this correct behaviour?

Yep! We might change that to a bool flag though... maybe something like `--subsystem` because that's only useful when Probr is being imported and used within another system (That feature was built to support the REST API that we prototyped)

**Comment by simonwoolhouse** [comment]
You're right. There's no point it being a CLI flag
