### ISSUE TITLE
"[BUG] Kubernetes scenario standard/none/AZ-AAD-AI-1.0 is missing a clause

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#78]
**Describe the bug**
This scenario is missing a second clause in the Given.

**To Reproduce**
n/a

**Expected behavior**
`And an AzureIdentityBinding exists in the default namespace called "probr-x-ns-test-aib"`

**Screenshots**
n/a

**Additional context**
n/a

**Comment by simonwoolhouse** [comment]
@iantivey should the action mapped to the new clause create the AzureIdentityBinding or simply check that it exists?
I'm assume the former, given that we can't assume that the named AIB would already have been created in the client's cluster
