### ISSUE TITLE
[BUG] Kubernetes services pack - mcr.microsoft.com should be "denied"

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#79]
**Describe the bug**
In the container registry tests mcr.microsoft.com is currently "allowed". This should be "denied".

**Expected behavior**
The container registry scenario for `mcr.microsoft.com` should pass if an attempt to deploy an image from that repo is denied.

**Screenshots**

**Additional context**
The only reason we need to pull from mcr.microsoft.com is to deploy the aad-pod-identity pods. However, we should deploy these into kube-system, which by default the "restrict container registries" policy is not applied.

**Comment by eddie-knight** [comment]
This was resolved by parameterizing the allowed/denied registries
