### ISSUE TITLE
[BUG] Kubernetes service pack - "allowed-registry" is not being replaced

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#80]
**Describe the bug**
In the container registry scenario test for `allowed-registry` we are passing the literal value `allowed-registry`. Instead it should be assigned/replaced at runtime with the value assigned to the configuration parameter `containerRegistry`

**To Reproduce**
Run the test

**Expected behavior**
The probe attempts to deploy the `config.probeImage` container image from `config.containerRegisitry`

**Screenshots**
n/a

**Additional context**
n/a

**Comment by simonwoolhouse** [comment]
@iantivey I propose that we change the config vars, so that both an 'AuthorisedContainerRegistry' and an 'UnauthorisedContainerRegistry' variable can be set and made mandatory.
The number of examples in the container_registry_access 2nd scenario outline (CIS-6.1.4) should be reduced to 2 - 1 authorised case and 1 unauthorised case.
Currently, the container_registry_access feature file specifies that mcr.microsoft.com is authorised, but the truth of this statement will clearly depend on the client.
Let me know if you agree with the approach

**Comment by iantivey** [comment]
If we're going to parameterise them they I think they both need to be represented as a list, but I'm not sure how well that works with BDD.  You might have to not use a scenario outline and have 2 separate scenarios for un/authorised, something like `**When** I attempt to pull images from a list of unauthorised container registries / **Then** all of the image pulls are denied`

What do you think?

**Comment by paulm-jones** [comment]
It's not a problem to use a list in BDD if we want.

Can do something like:

```
Given a list of authorised container registries
| citihubprivate.azurecr.io |
When I attempt to pull an image from "registry.gitlab.com"
Then the image pull is denied
```

**Comment by simonwoolhouse** [comment]
@iantivey I like the idea of replacing the scenario outline with 2 separate scenarios, each of which uses a configured list of container registries
The scenario will fail if a list is not provided as a config variable

**Comment by simonwoolhouse** [comment]
If we continue to explictly specify the authorised and unauthorised container registries in the feature file, then the user will need to config and maintain their own feature file. Is that what we want?

**Comment by eddie-knight** [comment]
> If we continue to explictly specify the authorised and unauthorised container registries in the feature file, then the user will need to config and maintain their own feature file. Is that what we want?

This assessment is accurate, and no- we don't want to require that. If we are probing for allowed and rejected repositories, we'll need to set those values from user-specified parameters. (Obviously we can provide defaults, which will be the most common allowed/rejected registries.)

**Comment by eddie-knight** [comment]
> you might have to not use a scenario outline and have 2 separate scenarios for un/authorised... Something like `**When** I attempt to pull images from a list of unauthorised container registries / **Then** all of the image pulls are denied`

@simonwoolhouse this is probably the best way of going about it. Two simple scenarios for allowed & denied, and then you'll check the config vars in the scenario function to determine what the corresponding registries are.
