### ISSUE TITLE
[FEATURE] Kubernetes service pack - use a single namespace

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#82]
**Is your feature request related to a problem? Please describe.**
The Kubernetes service pack creates a namespace for each feature.  In a real life scenario it's unlikely the credentials being used will have permission to create namespaces.  We should also avoid cluttering the cluster with namespaces for probr, so just use one.

**Describe the solution you'd like**
We should use a single namespace for all probes, default = `probr` but configurable at runtime.
If the namespace doesn't exist then we should attempt to create the namespace, otherwise fail the test in the `Given a Kubernetes cluster exists which we can deploy into` step.

**Comment by eddie-knight** [comment]
Namespace should be configurable by users
