### ISSUE TITLE
[FEATURE] Kubernetes service pack - decouple podsecuritypolicy implementation from tests

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#83]
**Is your feature request related to a problem? Please describe.**
In the PodSecurityPolicies tests the implementation of the steps such as, `And some system exists to prevent a Kubernetes deployment running with privileged access in an existing Kubernetes cluster`, look for specific resources deployed in the cluster.  This means the tests are tightly coupled to the exact implementation of the control.  This doesn't give us the flexibility to deploy to Kubernetes clusters that implement the control in a different way - for example, the test will currently fail when run against a Redhat Openshift cluster because they use `SecurityContextContraints` and we haven't implemented this specific implementation test (Azure uses Azure Policy, AWS and Google currently use PodSecurityPolicy... it's starting to fragment).  

**Describe the solution you'd like**
We should just assume these are in place and blindly pass these steps in our PSP scenarios.  Perhaps we can be explicit in our BDD by using the phrase "And we _assume_ some system exists...".  If the controls haven't been implemented then the other steps will fail. 

**Describe alternatives you've considered**
None - open to ideas

**Additional context**
Tightly coupling tests to the control implementation goes against what we're trying to achieve with Probr, which is to decouple ourselves from any specific implementation of the control and just focus on the behaviours.

**Comment by iantivey** [comment]
I think Paul's branch fixes this by removing the line from the BDD.

**Comment by eddie-knight** [comment]
Basically we'll just need to remove this line from every feature file:
`And some system exists to prevent a Kubernetes deployment running with privileged access in an existing Kubernetes cluster`

Additionally, we'll want to check for any other `And some system exists...` steps
