### ISSUE TITLE
[BUG] CIS-5.2.5 scenario is identical to CIS-5.2.1

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#9]
**Describe the bug**
(Originally reported by @daaadams)
This is for test CIS-5.2.5, "don't allow privileged escalation".  

Currently we're just running the same check as 5.2.1 ("//"but" same as 5.2.1 - line 251 in pod_security_feature.go) which is "chroot .".   This should probably be changed to "sudo chroot .".

**To Reproduce**
1. Open up the probr code
1. Look at the tests
1. 5.2.5 is the same as 5.2.1

**Expected behavior**
5.2.5 should attempt `sudo chroot .`

**Comment by lcarrazana** [comment]
TODO:
- [ ] Review CIS 5.2.1 and 5.2.5
- [ ] Update code

**Comment by rparupell** [comment]
The expectedExitCode=126 when we do sudo chroot . command which is different from the current expectedExitCode is 1.
We need to confirm the 126 is actual expected result.

We ran the test with 126 code, and the test runs successful.
