### ISSUE TITLE
[BUG] Add configurable set of capabilities to drop on every deployment

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#95]
**Is your feature request related to a problem? Please describe.**
If a cluster has pod security policy in place that enforces incoming Pod specs to drop specific capabilities all of our probes will fail to deploy.

**Describe the solution you'd like**
Ability to configure a list of capabilities that need to be dropped for everything we deploy (unless there's a reason not to, for example if we have a probe for that specific capability).

**Describe alternatives you've considered**
None

**Additional context**
https://www.redhat.com/en/blog/secure-your-containers-one-weird-trick

**Comment by lcarrazana** [comment]
Ref:
https://docs.docker.com/engine/reference/builder/#arg

**Comment by lcarrazana** [comment]
TODO:

- [ ] Replicate issue in demo cluster: attempting a pod deployment without dropping "NET_RAW" capability shall fail.
- [ ] Make appropriate changes in container specs to deploy successfully
- [ ] Add logic to specify a list of capabilities to drop and dynamically pass this list to any pod being deployed to cluster
- [ ] Create separate issue to troubleshoot / fix the following scenario:
`@k-psp-007`
`Scenario Outline: Prevent deployments from running with the NET_RAW capability.`

**Comment by lcarrazana** [comment]
TODO:

- [ ] Extend configurable setting to cases where CreatePodFromObject function is used
