### ISSUE TITLE
[FEATURE] Audit Log Panic Handling

### ISSUE THREAD

**Issue by eddie-knight** [citihub/probr#99]
**Is your feature request related to a problem? Please describe.**
If a probe fails due to panicing, cucumber will properly log the error but our audit logger will not. Due to the panic, the step is not logged, and the audit logger believes nothing has failed.

**Describe the solution you'd like**
Some additional layer to track that a function has begun, so that the audit logger will know if the step panicked and didn't finish.

**Describe alternatives you've considered**
N/A

**Additional context**
Resolving this will require some critical thinking around how we're currently handling audit data for each scenario.

**Comment by eddie-knight** [comment]
Use a defer function to audit on exit?

**Comment by eddie-knight** [comment]
Reopening this, as it seems we overlooked several k8s probes

**Comment by lcarrazana** [comment]
TODO - Add defered audit logic to the following K8s probes:
- [ ] general
- [ ] iam
- [ ] internet_access
- [ ] pod_security_policy
